config/routes.rb
Rails.application.routes.draw do
  
  # auth
  get '/login', to: 'sessions#new'
  post '/login', to: "sessions#create"
  post '/logout', to: "sessions#destroy", as: :logout
  
  # users
  resources :users, only: [:new, :create]
  

  # resources :products
  resources :categories do
    resources :products
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auth.rb
class Session < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :product_categories
    has_many :products, through: :product_categories

    has_many :sub_categories, class_name: "Category", foreign_key: :parent_id

    def has_sub_categories
        byebug
        cats = Category.where(parent_id: self.id)
        return cats
    end 
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :product_categories
    has_many :categories, through: :product_categories
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :valid?

    def user
        if session[:user]
            user = User.find(session[:user])
            user
        end
    end
    def valid?
        redirect_to login_path unless user
    end

    def current_user
        
        user_id = session[:user]
        
        if user_id
            user = User.find(user_id)
            "Welcome, #{user.username}!"
        else
            "Welcome to shopping site!"
        end
    end
    helper_method :current_user

end

app/controllers/auth_controller.rb
class AuthController < ApplicationController

    def index
    end

    def login
        user = User.find_by(username: params[:username])
        
        if user && user.authenticate(params[:password])
            redirect_to categories_path
        end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    def index
        @categories = Category.all.where(parent_id: nil)
    end

    def show
        @category = Category.find(params[:id])
        @test = @category.has_sub_categories
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :valid?, except: [:new, :create]
    
    def new
    end
    
    def create
        user = User.find_by(username: params[:username])
        
        if user && user.authenticate(params[:password])
            session[:user] = user.id
            redirect_to categories_path
        end
    end

    def destroy
        session.delete :user
        redirect_to login_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :valid? except: [:new, :create]
    def new
        
    end

    def create
        user = User.create(
            name: params[:name],
            username: params[:username],
            password: params[:password]
        )
        session[:user] = user.id
        redirect_to categories_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/categories/index.html.erb
<h2>Categories</h2> 

<%= form_with url: logout_path, method: "POST" do |f| %>
    <%= f.submit "logout" %>
<% end %>



<ul>
    <% @categories.each do |category| %>  
        <li>
            <%= link_to category_path(category) do %>
                <%= category.name %>
            <% end %>
        </li>
    <% end %>
</ul>

app/views/categories/show.html.erb
<h2> Category: <%= @category.name %> </h2>
<%= @test %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatSubcatExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p>
      <%= current_user %>
    </p>
    <hr/>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h2> Create New Account </h2>

<%= form_with url: user_path, method: "POST" do |user| %>
    <%= user.label :q, "Name" %>
    <%= user.text_field :name %>
    <br>
    <%= user.label :q, "Username" %>
    <%= user.text_field :username %>
    <br>
    <%= user.label :q, "Password" %>
    <%= user.password_field :password %>
    <br>
    <%= user.submit "Create Account" %>
    
<% end %>

app/views/users/new.html.erb
<h2> Create New Account </h2>

<%= form_with url: users_path, method: "POST" do |user| %>
    <%= user.label :q, "Name" %>
    <%= user.text_field :name %>
    <br>
    <%= user.label :q, "Username" %>
    <%= user.text_field :username %>
    <br>
    <%= user.label :q, "Password" %>
    <%= user.password_field :password %>
    <br>
    <%= user.submit "Create Account" %>
    
<% end %>